# Generated by Django 4.2.3 on 2023-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textanalysis',
            old_name='text',
            new_name='des',
        ),
    ]
