# Generated by Django 4.2.3 on 2023-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_text_textanalysis_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanalysis',
            name='des',
            field=models.CharField(max_length=255),
        ),
    ]
