# Generated by Django 4.2.3 on 2023-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_textanalysis_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='emotion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='textanalysis',
            name='des',
            field=models.TextField(),
        ),
    ]
