# Generated by Django 4.2.3 on 2023-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_textanalysis_emotion_alter_textanalysis_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(),
        ),
    ]
