# Generated by Django 4.2.3 on 2023-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_text_name_alter_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='predicted_emotion_emoticon',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='predicted_emotion_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
